### PR TITLE
Modify sections of Algozoo, recommendation and dp

### PR DESCRIPTION
**Pull request by DavdGao**
Modify path `flpackage` into `federatedscope`; 
Modify `reference` into `references`

### CODE REVIEW

**Review by joneswong — CHANGES_REQUESTED** [review]
As daoyuan's pr has been merged, there becomes a conflict. Please resolve it. BTW, please specify the layout for your tutorials.

**Comment by joneswong** [comment]
BTW, please also update the VLDB paper related article like what yuexiang has done for his paper.

**Comment by DavdGao** [comment]
The conflicts is resolved accordingly.

**Review by FederatedScopeTeam — CHANGES_REQUESTED** [review]
Please update the `excerptheader` of your publication post. The other two existing posts can be regarded as examples.

**Comment by DavdGao** [comment]
@FederatedScopeTeam The `excerptheader` is updated accordingly.

**Review by FederatedScopeTeam — APPROVED** [review]
approve!

**Review by joneswong — APPROVED** [review]
approve!

**Pull request merged**
